language: python

node_js:
  - node

cache:
  - npm
  - pip

python:
  - "3.9"

services:
  - postgresql

env:
  - GRAPHERY_NORMAL_LOG_PATH=graphery_normal.log GRAPHERY_EXECUTION_LOG_PATH=graphery_execution.log GRAPHERY_API_LOG_PATH=graphery_api.log PIPENV_IGNORE_VIRTUALENVS=1 

install:
  - sudo pip install pipenv
  - cd graphery
  - npm install -g yarn
  - yarn install

before_script:
  - psql -c 'create database graphery;' -U postgres
  - psql -c "create user graphery with encrypted password 'graphery';" -U postgres
  - psql -c 'ALTER USER graphery WITH SUPERUSER;' -U postgres
  - psql -c 'grant all privileges on database graphery to graphery;' -U postgres

script:
  - yarn run build
  - cd ../backend && sudo pipenv install -d && sudo pipenv sync && sudo pipenv graph
  - cd ./bundle && sudo pipenv run pytest -vv -ra -s
  - cd ../server && sudo pipenv run pytest -vv -ra -s
