language: python

nodoe_js:
  - node

cache:
  - npm
  - pip

python:
  - "3.8"

install:
  - pip install pipenv
  - cd graphery
  - npm install -g npm@latest
  - npm install

script:
  - npm run build
  - cd ../backend && pipenv install && sudo pipenv run pytest
