site_name: Graphery Docs
theme:
  name: material
site_description: The documentation site for Graphery
markdown_extensions:
  - pymdownx.details
  - codehilite
nav:
  - Home: "index.md"
  - "User Manual":
      - "Get Started": "./user-manual/get-started.md"
  - "Backend Doc":
      - "Utilities": "./backend-docs/utils.md"
      - "Databse Schema": "./backend-docs/database-specification.md"
      - "Naming Conventions": "./backend-docs/naming-convention.md"
      - "CLI Usages": "./backend-docs/cli-usages.md"
      - "APIs": "./backend-docs/api-specification.md"
  - About: "about.md"
